spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/moveiidb
    username: moveii
    password: moveii
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create