spring:
  datasource:
    url: jdbc:h2:mem:testdb;init=drop sequence if exists alerts_seq\;create sequence alerts_seq;
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update