DROP TABLE IF EXISTS LOGBOOK.TRANSITIONS;
DROP TABLE IF EXISTS LOGBOOK.NOTES;
DROP TABLE IF EXISTS LOGBOOK.ASSIGNEE_HISTORY;
DROP TABLE IF EXISTS LOGBOOK.ALERTS;
DROP TABLE IF EXISTS LOGBOOK.LOG_MESSAGES;
-- DROP TABLE IF EXISTS logbook.users;
DROP SCHEMA LOGBOOK;